name: Shell Commands 

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello Marlene Tapia!!"
        timeout-minutes: 0
      - name: multiline script 
        run: |
           node -v 
           npm -v
